# Generated by Django 3.1.2 on 2021-08-15 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=50)),
                ('developer', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('release_date', models.DateField(verbose_name='release date')),
                ('can_sell', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('box_art', models.URLField(default='')),
                ('esrb_rating', models.URLField(default='')),
            ],
        ),
    ]
