# Generated by Django 3.1.2 on 2021-08-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_art',
        ),
    ]
