# Generated by Django 3.1.2 on 2021-08-16 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='shop_id',
            new_name='shop',
        ),
    ]
