# Generated by Django 3.1.2 on 2021-08-18 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210815_1336'),
        ('products', '0008_auto_20210816_0917'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('shop', 'product')},
        ),
    ]
