# Generated by Django 3.1.2 on 2021-09-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210901_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='platforms',
            field=models.CharField(default='', max_length=500),
        ),
    ]
