# Generated by Django 3.1.2 on 2021-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_stock_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
        migrations.AddField(
            model_name='stock',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
