# Generated by Django 3.1.2 on 2021-10-15 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20211015_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
