# Generated by Django 3.1.2 on 2021-10-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20211015_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend_id',
            new_name='friend',
        ),
    ]
