# Generated by Django 3.1.2 on 2021-10-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0004_auto_20211015_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friend',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friend',
            old_name='user',
            new_name='sender',
        ),
    ]
