# Generated by Django 3.1.2 on 2021-10-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0005_auto_20211020_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confrimed', 'confrimed')], default='pending', max_length=50),
        ),
    ]
