# Generated by Django 3.1.2 on 2021-10-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0006_auto_20211020_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='status',
        ),
        migrations.AddField(
            model_name='friend',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
