# Generated by Django 3.1.2 on 2021-10-22 21:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0007_auto_20211020_2238'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('sender', 'receiver')},
        ),
    ]
