# Generated by Django 3.1.2 on 2021-10-22 21:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friend', '0008_auto_20211022_2343'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('receiver', 'sender'), ('sender', 'receiver')},
        ),
    ]
