# Generated by Django 3.1.2 on 2021-10-22 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0009_auto_20211022_2344'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set(),
        ),
    ]
