# Generated by Django 3.1.2 on 2021-08-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='esrb_rating',
            field=models.URLField(default=''),
        ),
    ]
