# Generated by Django 3.1.2 on 2021-08-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_esrb_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_art',
        ),
    ]
