# Generated by Django 3.1.2 on 2021-08-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_product_box_art'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_art',
            field=models.URLField(default=''),
        ),
    ]
