# Generated by Django 3.1.2 on 2021-08-15 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_box_art'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
