# Generated by Django 3.1.2 on 2021-09-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_profile'),
        ('user_profile', '0003_auto_20210929_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('likes', models.ManyToManyField(related_name='post_likes', to='users.Customer')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='fiends_list', to='users.Customer'),
        ),
        migrations.DeleteModel(
            name='PostComments',
        ),
        migrations.AddField(
            model_name='postdata',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.post'),
        ),
    ]
