# Generated by Django 3.1.2 on 2021-09-29 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_profile'),
        ('user_profile', '0004_auto_20210929_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='post_likes', to='users.Customer'),
        ),
    ]
