# Generated by Django 3.1.2 on 2021-09-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_profile'),
        ('user_profile', '0007_auto_20210929_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postdata',
            name='post',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='PostData',
        ),
    ]
