# Generated by Django 3.1.2 on 2021-09-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_auto_20210929_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='email',
        ),
    ]
