# Generated by Django 3.1.2 on 2021-09-29 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0013_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('confirmed', 'confirmed'), ('none', 'none')], max_length=50),
        ),
    ]
