# Generated by Django 3.1.2 on 2021-09-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0017_auto_20210929_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email',
            new_name='author',
        ),
    ]
