# Generated by Django 3.1.2 on 2021-10-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0018_auto_20210929_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
