# Generated by Django 3.1.2 on 2021-10-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0020_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
