# Generated by Django 3.1.2 on 2021-10-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0022_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.IntegerField(blank=True, default='default_profile_pic.png', null=True),
        ),
    ]
