# Generated by Django 3.1.2 on 2021-10-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0023_auto_20211003_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile_pic.png', null=True, upload_to=''),
        ),
    ]
