# Generated by Django 3.1.2 on 2021-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0024_auto_20211003_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Anon', max_length=50),
        ),
    ]
