# Generated by Django 3.1.2 on 2021-10-03 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0025_auto_20211003_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
