# Generated by Django 3.1.2 on 2021-10-15 18:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import upload.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0004_auto_20211015_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_pic.svg', upload_to=upload.models.user_directory_path)),
                ('date_added', models.DateTimeField(default=datetime.datetime(2021, 10, 15, 20, 24, 51, 259966))),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
