# Generated by Django 3.1.2 on 2021-10-16 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20211015_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userupload',
            name='post',
        ),
        migrations.RemoveField(
            model_name='userupload',
            name='user',
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 18, 0, 5, 727235)),
        ),
    ]
