# Generated by Django 3.1.2 on 2021-10-16 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20211016_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 18, 5, 28, 356680)),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='upload_type',
            field=models.CharField(choices=[('profile_pic', 'profile_pic'), ('post', 'post'), ('default', 'default')], default='default', max_length=50),
        ),
    ]
