# Generated by Django 3.1.2 on 2021-10-16 16:07

import datetime
from django.db import migrations, models
import upload.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20211016_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 18, 7, 21, 828061)),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='image',
            field=models.ImageField(upload_to=upload.models.user_directory_path),
        ),
    ]
