# Generated by Django 3.1.2 on 2021-10-16 16:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0005_auto_20211016_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='user',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userupload',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 18, 10, 5, 148448)),
        ),
    ]
