# Generated by Django 3.1.2 on 2021-10-16 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20211016_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 20, 8, 50, 7412)),
        ),
    ]
