# Generated by Django 3.1.2 on 2021-10-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20211016_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
