# Generated by Django 3.1.2 on 2021-09-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210928_1534'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
