# Generated by Django 3.1.2 on 2021-10-02 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='full_name',
        ),
    ]
