# Generated by Django 3.1.2 on 2021-10-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='author',
            new_name='user',
        ),
    ]
