# Generated by Django 3.1.2 on 2021-10-15 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211015_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='comment_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
