# Generated by Django 3.1.2 on 2021-10-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_postcomment_comment_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postcommentsentiment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='postlike',
            name='user',
        ),
    ]
