# Generated by Django 3.1.2 on 2021-10-15 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0004_auto_20211015_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(default='nothing', on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcommentsentiment',
            name='user',
            field=models.ForeignKey(default='nothing', on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(default='nothing', on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
    ]
