# Generated by Django 3.1.2 on 2021-10-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlike',
            name='liked',
            field=models.BooleanField(default=True),
        ),
    ]
