# Generated by Django 3.1.2 on 2021-10-21 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_postlike_liked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='liked',
            new_name='is_liked',
        ),
    ]
