# Generated by Django 3.1.2 on 2021-10-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20211021_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='user',
            new_name='commenter',
        ),
    ]
