# Generated by Django 3.1.2 on 2021-10-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20211024_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='op',
        ),
    ]
