# Generated by Django 3.1.2 on 2021-10-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20211024_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='comment',
            new_name='text',
        ),
    ]
