# Generated by Django 3.1.2 on 2021-10-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20211024_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcommentsentiment',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='postcommentsentiment',
            name='is_disliked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postcommentsentiment',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
