# Generated by Django 3.1.2 on 2021-10-31 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20211025_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 54, 52, 151815)),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 31, 13, 54, 52, 152827)),
        ),
    ]
