# Generated by Django 3.1.2 on 2021-10-13 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211010_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('bio', models.TextField(max_length=500, null=True)),
                ('interests', models.TextField(max_length=500, null=True)),
                ('education', models.CharField(max_length=250, null=True)),
                ('rel_status', models.CharField(choices=[('single', 'single'), ('engaged', 'engaged'), ('married', 'married')], max_length=50, null=True)),
                ('job_status', models.CharField(max_length=250, null=True)),
                ('location', models.CharField(max_length=250, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
