# Generated by Django 3.1.2 on 2021-10-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211013_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_visibility', models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('private', 'private')], default='friends', max_length=50)),
                ('profile_visibility', models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('private', 'private')], default='friends', max_length=50)),
                ('personal_info_visibility', models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('private', 'private')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
