# Generated by Django 3.1.2 on 2021-10-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
