# Generated by Django 3.1.2 on 2021-10-16 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20211016_1800'),
        ('users', '0009_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload.userupload'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='personal_info_visibility',
            field=models.CharField(choices=[('public', 'public'), ('friends', 'friends'), ('private', 'private')], default='friends', max_length=50),
        ),
    ]
