# Generated by Django 3.1.2 on 2021-10-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
    ]
