# Generated by Django 3.1.2 on 2021-10-17 19:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211016_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='abc_0101_11223.svg', null=True, upload_to=users.models.user_directory_path),
        ),
    ]
