# Generated by Django 3.1.2 on 2021-10-17 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20211018_0147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
