# Generated by Django 3.1.2 on 2021-10-23 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersetting',
            name='personal_info_visibility',
        ),
    ]
