# Generated by Django 3.1.2 on 2021-10-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_usersetting_upload_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
