# Generated by Django 3.1.2 on 2021-10-25 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('accepted_request', 'accepted_request'), ('received_request', 'received_request'), ('post_comment', 'post_comment')], max_length=100),
        ),
    ]
