# Generated by Django 3.1.2 on 2021-11-03 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20211025_1118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
