# Generated by Django 3.1.2 on 2021-09-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type_of', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('region', models.CharField(max_length=200)),
            ],
        ),
    ]
