# Generated by Django 3.1.2 on 2021-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customerproductreview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerproductreview',
            old_name='rating',
            new_name='product_rating',
        ),
        migrations.AddField(
            model_name='customerproductreview',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
