# Generated by Django 3.1.2 on 2021-09-21 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210921_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='product_rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
