# Generated by Django 3.1.2 on 2021-09-21 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210921_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='product_rating',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
