# Generated by Django 3.1.2 on 2021-09-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210921_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='product_rating',
            field=models.IntegerField(default=0),
        ),
    ]
