# Generated by Django 3.1.2 on 2021-09-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210921_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='review',
            field=models.CharField(max_length=500),
        ),
    ]
