# Generated by Django 3.1.2 on 2021-09-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210922_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='review',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
