# Generated by Django 3.1.2 on 2021-09-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210922_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='review',
            field=models.TextField(max_length=500),
        ),
    ]
