# Generated by Django 3.1.2 on 2021-09-23 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_customerproductreview_product_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproductreview',
            name='likes',
        ),
    ]
