# Generated by Django 3.1.2 on 2021-09-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210920_1549'),
        ('product', '0014_remove_customerproductreview_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductreview',
            name='likes',
            field=models.ManyToManyField(related_name='product_review', to='users.Customer'),
        ),
    ]
