# Generated by Django 3.1.2 on 2021-09-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210920_1549'),
        ('product', '0016_auto_20210925_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproductreview',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='product_review_dislikes', to='users.Customer'),
        ),
        migrations.AlterField(
            model_name='customerproductreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='product_review_likes', to='users.Customer'),
        ),
    ]
