# Generated by Django 3.1.2 on 2021-10-02 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0021_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='customer',
        ),
        migrations.AddField(
            model_name='productreview',
            name='author',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
    ]
