# Generated by Django 3.1.2 on 2021-10-02 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20211002_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date_posted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
