# Generated by Django 3.1.2 on 2021-10-02 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_productreview_date_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewsentiment',
            name='customer',
        ),
        migrations.AddField(
            model_name='productreviewsentiment',
            name='user',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='users.newuser', to_field='email'),
            preserve_default=False,
        ),
    ]
