# Generated by Django 3.1.2 on 2021-10-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20211002_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
