# Generated by Django 3.1.2 on 2021-08-15 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_newuser_shop_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.newuser')),
                ('shop_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.newuser',),
        ),
    ]
