# Generated by Django 3.1.2 on 2021-08-15 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='location',
        ),
        migrations.AddField(
            model_name='shop',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 6, 53, 44, 243368, tzinfo=utc)),
        ),
    ]
