# Generated by Django 3.1.2 on 2021-08-15 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210815_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
