# Generated by Django 3.1.2 on 2021-09-25 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0019_productreviewsentiment'),
        ('users', '0008_auto_20210920_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ManyToManyField(to='users.Customer')),
                ('product', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
