# Generated by Django 3.1.2 on 2021-09-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='platforms',
            field=models.CharField(default='', max_length=500),
        ),
    ]
