# Generated by Django 3.1.2 on 2021-09-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='platforms',
        ),
        migrations.AddField(
            model_name='booking',
            name='platform',
            field=models.CharField(default='', max_length=50),
        ),
    ]
