# Generated by Django 3.1.2 on 2021-09-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20210901_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
