# Generated by Django 3.1.2 on 2021-09-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20210903_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_complete',
            new_name='is_arrived',
        ),
    ]
